### ISSUE TITLE
Issues with new themes

### ISSUE THREAD

**Issue by rubybrowncoat** [manfroze/keydraw#10]
You can barely see that you have selected white when you are on the light theme:
![image](https://user-images.githubusercontent.com/973824/36146363-ae095170-10b4-11e8-9629-800bc7b247dd.png)

And there's a white margin at the bottom of the page:
![image](https://user-images.githubusercontent.com/973824/36146409-d3407e1e-10b4-11e8-8c3b-911032388de3.png)

**Comment by manfroze** [comment]
Fixed the white space. For the color I guess I'll tweak everything until it makes sense.

**Comment by rubybrowncoat** [comment]
You didn't fix shit. You just made the wrapper 200vh high. What happens when the grid is 220vh high?

**Comment by manfroze** [comment]
That wasn't the fix, just an error. The fix was removing a big margin-bottom. However, now everything changed...!

**Comment by rubybrowncoat** [comment]
When the Fire Nation attached.
